/**
 * Non-mocked integration test for PiHarness auth.json resolution (TDD RED step)
 *
 * @remarks
 * This test exercises the REAL `node_modules/groundswell` PiHarness (not vitest-aliased)
 * by spawning a tsx subprocess. The subprocess has no vitest resolve alias, so its
 * `import 'groundswell'` resolves to the stale `node_modules/groundswell` dist.
 *
 * WHY SUBPROCESS (mandatory — do NOT "simplify" to in-process await):
 *   vitest.config.ts sets `resolve.alias.groundswell` → the sibling checkout at
 *   `../groundswell/dist/index.js` (the FIXED dist with `AuthStorage.create()`).
 *   An in-process `await harness.authStorage.getApiKey('zai')` would load the FIXED
 *   dist via the alias and silently PASS (GREEN), never reproducing the bug. The
 *   subprocess has no alias → hits the real stale dist → produces a genuine RED.
 *
 * Case A (auth.json-only): RED today — getApiKey('zai') returns undefined on the stale
 *   dist. Turns GREEN after P1.M1.T2 deploys the fixed Groundswell dist
 *   (`AuthStorage.create()` reads auth.json).
 *
 * Case B (ZAI_API_KEY-only control): GREEN today — env key works on the stale dist too
 *   (env-var fallback is built into `AuthStorage.getApiKey`). Proves the bug is specific
 *   to auth.json, not a general harness failure.
 *
 * @see plan/007_8783a1f5e14a/bugfix/001_7912d248208a/P1M1T1S1/research/alias-conflict-and-subprocess-approach.md
 */

import { describe, expect, it, afterEach, beforeEach } from 'vitest';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, rmSync, unlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Path to the tsx binary (subprocess transpiles TS → runs without vitest alias). */
const TSX = resolve('node_modules/.bin/tsx');

/**
 * Path to the runner script written to the PROJECT ROOT at runtime.
 * Must live inside the project tree so bare `import 'groundswell'` resolves to
 * `node_modules/groundswell`. Cleaned up in afterEach. NOT committed.
 */
const RUNNER = resolve('_pi-harness-auth-runner.mjs');

/**
 * Auth-related env vars that MUST be cleared in the subprocess to prevent
 * a developer's real credentials from leaking in and making the test
 * non-deterministic.
 */
const AUTH_VARS = [
  'ZAI_API_KEY',
  'PRP_API_KEY',
  'ANTHROPIC_API_KEY',
  'ANTHROPIC_AUTH_TOKEN',
  'ANTHROPIC_OAUTH_TOKEN',
  'PRP_AGENT_HARNESS',
  'ANTHROPIC_DEFAULT_SONNET_MODEL',
] as const;

/**
 * Runner script source — executed in a tsx SUBPROCESS (no vitest alias).
 *
 * NO mocking of any kind. `import 'groundswell'` resolves to the real
 * `node_modules/groundswell` dist (stale). `import './src/config/harness.ts'`
 * resolves to repo source.
 *
 * Prints a machine-parseable line: `RESULT key=<JSON>` or `RESULT ERROR=<msg>`.
 */
const RUNNER_SRC = `// Auto-generated by pi-harness-auth.test.ts — do NOT edit or commit.
// Top-level await is legal in .mjs.
try {
  const { ensureHarnessInitialized } = await import('./src/config/harness.ts');
  const { HarnessRegistry } = await import('groundswell');       // resolves to node_modules/groundswell in the subprocess
  await ensureHarnessInitialized();
  const h = HarnessRegistry.getInstance().get('pi');
  const key = await h?.authStorage?.getApiKey('zai');            // async; nullable authStorage guarded with ?.
  process.stdout.write('RESULT key=' + JSON.stringify(key));
} catch (e) {
  process.stdout.write('RESULT ERROR=' + (e?.message ?? String(e)));
} finally {
  try { const { HarnessRegistry } = await import('groundswell'); await HarnessRegistry.getInstance()?.get('pi')?.terminate?.(); } catch {}
}
`;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Write the runner script to the project root (beforeEach).
 */
beforeEach(() => {
  writeFileSync(RUNNER, RUNNER_SRC);
});

/**
 * Remove the runner script from the project root (afterEach).
 */
afterEach(() => {
  try {
    unlinkSync(RUNNER);
  } catch {
    // Already removed or never written — safe to ignore.
  }
});

/**
 * Spawn a tsx subprocess exercising the REAL `node_modules/groundswell` PiHarness
 * and return the parsed `getApiKey('zai')` value.
 *
 * @param opts.seedAuthJson - If true, writes `{ zai: { type: 'api_key', key: 'SECRET-FROM-AUTH-JSON' } }`
 *   to `auth.json` inside the temp `PI_CODING_AGENT_DIR`.
 * @param opts.extraEnv - Additional env vars to set on the subprocess (e.g. `{ ZAI_API_KEY: '...' }`).
 * @returns The parsed key value (string) or undefined.
 */
function runCase(opts: {
  seedAuthJson?: boolean;
  extraEnv?: Record<string, string>;
}): string | undefined {
  const tmp = mkdtempSync(join(tmpdir(), 'pi-auth-'));
  try {
    // Seed auth.json if requested (must happen BEFORE the subprocess reads it).
    if (opts.seedAuthJson) {
      writeFileSync(
        join(tmp, 'auth.json'),
        JSON.stringify({
          zai: { type: 'api_key', key: 'SECRET-FROM-AUTH-JSON' },
        })
      );
    }

    // Build a clean env: copy process.env, strip ALL auth vars, set PI_CODING_AGENT_DIR.
    const env: Record<string, string | undefined> = { ...process.env };
    for (const k of AUTH_VARS) {
      delete env[k];
    }
    env.PI_CODING_AGENT_DIR = tmp;
    if (opts.extraEnv) {
      Object.assign(env, opts.extraEnv);
    }

    // Spawn tsx subprocess (no vitest alias → hits real node_modules/groundswell).
    const res = spawnSync(TSX, [RUNNER], {
      env: env as NodeJS.ProcessEnv,
      encoding: 'utf8',
      timeout: 30_000,
    });

    // Parse the runner's RESULT protocol line from stdout.
    const m = (res.stdout ?? '').match(/RESULT key=(.*)$/m);
    if (!m) {
      throw new Error(
        `runner produced no RESULT line\nstdout:${res.stdout}\nstderr:${res.stderr}`
      );
    }

    const raw = m[1].trim();
    // `JSON.stringify(undefined)` produces the literal string `undefined` (not JSON null).
    return raw === 'undefined' ? undefined : (JSON.parse(raw) as string);
  } finally {
    // Always clean up the temp dir (auth.json inside).
    rmSync(tmp, { recursive: true, force: true });
  }
}

// ---------------------------------------------------------------------------
// Test cases
// ---------------------------------------------------------------------------

describe('PiHarness auth.json resolution (non-mocked, real node_modules/groundswell)', () => {
  it('auth.json-only: getApiKey(zai) resolves the on-disk credential', () => {
    // RED today: stale dist uses AuthStorage.inMemory() → getApiKey returns undefined.
    // GREEN after P1.M1.T2: fixed dist uses AuthStorage.create() → reads auth.json.
    const key = runCase({ seedAuthJson: true });
    expect(key).toBe('SECRET-FROM-AUTH-JSON');
  });

  it('ZAI_API_KEY-only (no auth.json): getApiKey(zai) resolves the env value (control)', () => {
    // GREEN on both stale and fixed dists — env var fallback is built into
    // AuthStorage.getApiKey(). Proves the bug is specific to auth.json.
    const key = runCase({
      seedAuthJson: false,
      extraEnv: { ZAI_API_KEY: 'SECRET-FROM-ENV' },
    });
    expect(key).toBe('SECRET-FROM-ENV');
  });
});
